問１：  
One Hot Encodingについて調べて、自分なりの言葉で説明できるように準備してください。

In [1]:
# 行を列に変更し0か1で表示する
# 数値として扱えないデータを数値に変更するのが目的

「data.csv」を読み込んで、pandas の機能を使って、「商品」列を One Hot Encoding し、結果を表示してください。

In [3]:
# 必要なライブラリを読み込む
import pandas as pd

In [4]:
# 「data.csv」を読み込んで、df に データを格納する
df = pd.read_csv("data.csv", encoding = "shift-jis")

# df の内容を表示する
df

        商品   価格
0    りんごあめ  300
1   チョコバナナ  200
2     やきそば  500
3     たこ焼き  550
4  スーパーボール  100

In [5]:
# df から 商品列だけを抜き出し、df2 に代入する
# DataFrame['カラム名']で取得するとSeries型、DataFrame[['カラム名']]で取得するとDataFrame型です！！！！
df2 = df[["商品"]]

# df2の内容を表示
df2

        商品
0    りんごあめ
1   チョコバナナ
2     やきそば
3     たこ焼き
4  スーパーボール

In [7]:
#  df2 の中身を One Hot Encoding し、newdf に代入する
newdf = pd.get_dummies(df2, prefix = "商品")

# newdfの中身を表示
newdf

   商品_たこ焼き  商品_やきそば  商品_りんごあめ  商品_スーパーボール  商品_チョコバナナ
0        0        0         1           0          0
1        0        0         0           0          1
2        0        1         0           0          0
3        1        0         0           0          0
4        0        0         0           1          0